### PR TITLE
AEROGEAR-3591 restyled tabs

### PR DESCRIPTION
**Pull request by pawelpaszki**
## JIRA

https://issues.jboss.org/browse/AEROGEAR-3951

## Motivation

Restyling tabs as shown in screenshots below

## Screenshot before:

tabs_before

## Screenshot after:

tabs_after_short

### CODE REVIEW

**Comment by pawelpaszki** [comment]
@jasonmadigan @finp what do you think guys?

**Comment by jasonmadigan** [comment]
@pawelpaszki much improved

**Comment by finp** [comment]
looks really good, 
@johnfriz  I've posted a build using these tabs to https://finp.github.io/
The only question I'd have is whether we should reduce the font size so that the four platforms would render on one line for a mobile device?

**Comment by finp** [comment]
@pawelpaszki  your screenshot shows the tab only consuming the space of the text, but my build shows the 'white' all the way to the right of page, deliberate decision?

**Comment by johnfriz** [comment]
screenshot 2018-07-03 21 53 03

An alternate approach, which I think ties in better with the site nav

Main css changes:
```
.switch--item {
  padding: 7px;
  background-color: #2e6980;
  color: #a7c9d9;
  cursor: pointer;
  border: 1px solid #aaa;
  /* border-radius: 10px; */
}

.switch--item.selected {
  -webkit-box-shadow: inset 0 4px 0 #ffd400!important;
  box-shadow: inset 0 4px 0 #ffd400!important;
  color: #fff;
  /* border-radius: 10px; */
}

.sidebarblock.primary {
  padding-top: 0px;
  padding-left: 0px;
  padding-right: 0px;
}

.sidebarblock.primary>content {
  padding-left: 15px;
  padding-right: 15px;
  margin-top: -15px; 
  margin-bottom: -9px;
}
```

**Comment by jasonmadigan** [comment]
thanks @pawelpaszki. Some small bits from chatting to @johnfriz & @finp :

- Remove the grey background around the "tab heading" (leave for content)
- Add left & right padding for the content area (15px)

screen shot 2018-07-04 at 10 02 14

**Comment by pawelpaszki** [comment]
@jasonmadigan @johnfriz @finp I have removed the grey border around individual tabs and the radius border around the whole tabs element. I have also added a border around images.

**Comment by pawelpaszki** [comment]
ping @jasonmadigan

**Comment by pawelpaszki** [comment]
@jasonmadigan 

## Tabs:

tabs

## Image border:

image_border

**Comment by johnfriz** [comment]
@jasonmadigan - do we want any border around the tabs to delineate between them, or are we OK with it being a continuous bar? As it is right now, it actually looks closer to the top Nav, so no border on the tabs is probably the right approach.

**Comment by jasonmadigan** [comment]
@johnfriz think we're OK TBH

**Comment by johnfriz** [comment]
@jasonmadigan - Agreed. Ship it!!

**Comment by jasonmadigan** [comment]
@pawelpaszki I'll run pack to generate a bundle

**Comment by jasonmadigan** [comment]
packed, pushed.

**Pull request merged**
