### PR TITLE
fixed img border

### PR DESCRIPTION
**Pull request by pawelpaszki**
@jasonmadigan updated the css. Packed it as well

### CODE REVIEW

**Comment by jasonmadigan** [comment]
@pawelpaszki perfect

**Comment by jasonmadigan** [comment]
@pawelpaszki weird, wondering why it's showing a conflict on a binary file...

**Comment by pawelpaszki** [comment]
@jasonmadigan noticed it as well. Maybe we should pack again?

**Comment by jasonmadigan** [comment]
@pawelpaszki yeah, lets pack once more

**Comment by jasonmadigan** [comment]
@pawelpaszki just re-packed - included you changes!

**Comment by jasonmadigan** [comment]
fixed in https://github.com/aerogear/antora-ui/commit/e8f6614586cebf7cefb87fdde4a6e66347a13b8b

**Comment by pawelpaszki** [comment]
@jasonmadigan Thanks!

**Comment by jasonmadigan** [comment]
@pawelpaszki np - thanks for help!

**Comment by jasonmadigan** [comment]
@pawelpaszki that is published now

**Pull request closed without merging**
