### PR TITLE
Restyle docs

### PR DESCRIPTION
**Pull request by maleck13**

### CODE REVIEW

**Comment by maleck13** [comment]
@jasonmadigan ping restyle changes here

**Comment by jasonmadigan** [comment]
@maleck13 will take a look now

**Comment by jasonmadigan** [comment]
changes

**Comment by jasonmadigan** [comment]
@maleck13 added a hover state

**Comment by maleck13** [comment]
@finp restyle here. Do we need to do more than merge it to get it into the actual docs?

**Comment by finp** [comment]
@maleck13  Thanks, but I'm not seeing logo:
To replicate:
1. Install antora (https://docs.antora.org/antora/1.0/install/install-antora/)
2. Download https://github.com/finp/mobile-docs/blob/restyle-docs/restyle-docs.yml
3 Run 
antora restyle-docs.yml

Browse ./build/site/index.html

**Comment by maleck13** [comment]
ok 👀

**Comment by maleck13** [comment]
should be ok now

**Comment by finp** [comment]
@maleck13  looks good, thanks

**Pull request merged**
