### PR TITLE
Hide the navbar for showcase apps - hit with #nochrome

### PR DESCRIPTION
**Pull request by jasonmadigan**
http://localhost:5252/

screen shot 2018-07-02 at 15 14 31

http://localhost:5252/#nochrome

screen shot 2018-07-02 at 15 14 15

### CODE REVIEW

**Comment by jasonmadigan** [comment]
@johnfriz @finp @sedroche FYI

**Comment by jasonmadigan** [comment]
@sedroche amended last commit with your patch

**Comment by jasonmadigan** [comment]
Will rebase.

**Comment by finp** [comment]
@sedroche what webserver did you use to test this?

**Comment by jasonmadigan** [comment]
@sedroche @pmacko1 - rebased

**Comment by jasonmadigan** [comment]
Merging after chatting to @pmacko1

**Pull request merged**
