### PR TITLE
add application security on dropdown and footer

### PR DESCRIPTION
**Pull request by austincunningham**
## Motivation
https://issues.jboss.org/browse/AEROGEAR-8692

## What
Add Application Security to services

## Why
documentation

## How
add a drop down and footer link. 

## Verification Steps
- clone this repo
- checkout this branch
- cd ./atora-ui
- nvm use 8
- npm i
- npm i -g gulp-cli
- gulp preview
- access the preview at http://localhost:5252
- check the `Application Security` drop down and and the footer for the links 

aerogear-docs

## Checklist:

- [x] Code has been tested locally by PR requester
- [ ] Changes have been successfully verified by another team member

### CODE REVIEW

**Review by davidffrench — APPROVED** [review]
Fantastic job @austincunningham

**Comment by pwright** [comment]
@austincunningham @davidffrench  This looks good but shouldn't be merged until aerogear.org is updated

**Comment by davidffrench** [comment]
@laurafitzgerald This PR related to MSS may already be on your radar but if not, wanted to ping you on it as an FYI.

**Comment by pwright** [comment]
closing as out of date as per https://issues.jboss.org/browse/AEROGEAR-9151

**Pull request closed without merging**
