### PR TITLE
Update header and footer to match main website

### PR DESCRIPTION
**Pull request by sedroche**
Updating header and footer to match the aerogear.org.

new-header-and-footer

new header
new-footer

### CODE REVIEW

**Comment by finp** [comment]
@sedroche  seems to obscure headings, for example, see https://finp.github.io/aerogear/latest/identity-management.html

**Comment by sedroche** [comment]
@finp Will take a look thanks

**Comment by sedroche** [comment]
@finp I have added some changes to address your feedback if you want to take a second look

**Comment by pmacko1** [comment]
tried locally, looks ok

**Pull request merged**
